### ISSUE TITLE
Add Neovim Editor to WARP Box

### ISSUE THREAD

**Issue by mrzzy** [mrzzy/warp#3]
# Why?
A good editor is the bedrock of a usable development environment.

# How?
- [x] Add Ansible Role to deploy neovim
- [x] Add `neovim` via APT
- [x] Pull `init.vim` config from [dotfiles repo](https://github.com/mrzzy/dotfiles)
- [x] Install vim-plug plugin manager.
  -  [x] gutentagss with universal ctags.
  -  [x] f[zf.vim finder](https://github.com/junegunn/fzf.vim)
  -  [x] vim-obsession for session saving.
- [x] Add role to install nodeJS via [Node Source](https://github.com/nodesource/distributions/blob/master/README.md#deb)
```yaml
- name: Download setup_8.x script
  get_url: url=https://deb.nodesource.com/setup_8.x dest=/opt mode=755
- name: Setup Node.js
  command: /opt/setup_8.x
- name: Install Node.js (JavaScript run-time environment)
  apt: name=nodejs state=present
```
- [x] Install coc.nvim with the following language support:
   - [x] Python (coc-pyright)
   - [x] yaml
- [x] Install `ripgrep` and hook it up to `:grep`.
- [x] UI
    - [x] Gruvbox material colors
- [x] Keybinds:
  - [x] Ctrl-p like file jumping using fzf.vim
